### ISSUE TITLE
bats-core naming

### ISSUE THREAD

**Issue by jasonkarns** [ztombol/bats-support#4]
A point of confusion that I had at first, and potentially for others, is the bats-core name. Even as someone who has been following this stdlib extraction for a while, the bats-core name suggests it is the "core" component of bats. ie, the runner.

rspec is similarly broken down into component gems:
- rspec-core being the runner
- rspec-expectations being the assertions
- rspec-mocks for stubs/doubles/mocks
- rspec-support being the shared lib used by all rspec-\* gems

rspec-support plays the same role in the rspec ecosystem as this bats-core does, but IMO, is better named. 

Without any context or history, I don't believe someone could successfully guess the roles or distinction between bats and bats-core.

I propose that bats-core be renamed as bats-support or bats-internal or bats-lib (ordered per my preference). Obviously project renames are dangerous and should be done rarely and with caution. It is for this reason I am raising this issue now, so that it can be done ASAP (if at all), before we hit 1.0.

**Comment by ztombol** [comment]
I've been expecting this to come up even before I created the repos. The whole development took way too long and I just wanted the libraries to be out there so people can try them and we can receive feedback. At the time I was more concerned about `bats-docs` being misleading. Didn't think `bats-core` would be a point of confusion since `bats` is standalone. But your analogy with `rspec` highlights that indeed the naming is pretty murky.

Back then, I though it would be transferred into a community organisation that would set it somewhat apart, but having a clear name is better of course. I'm okay with `bats-support`.

How about `bats-docs`? That still looks to me that it hosts Bats' documentation. Renaming the whole array of repos to use a `batslib-` prefix instead of `bats-` could solve it (in addition to renaming `bats-core` as you suggested). But maybe its just me.

You and some of the people who contributed to the discussion in that pull request have much more experience with testing and frameworks than I do. So I'm willing to rename to follow the naming habits of other test frameworks, or any other way suggested. 

Renaming is a hassle, so it's good you brought it up early. According to the [help](https://help.github.com/articles/renaming-a-repository/), GitHub's handling it quite graciously. It redirects browsers, pulls, stars, etc.

**Comment by jasonkarns** [comment]
I don't have a strong opinion on `bats-*` vs `batslib-*`. All things being equal, I think shorter is better. And if everything went into an org:

`bats/bats`, `bats/bats-support`, `bats/bats-assert` seems fine to me. I'm less concerned about bats-docs because that's not a repo that would be installed by users. (I think bats-docs is fine)

Having done repo renames as well as repo moves (to different owners and/or to orgs), github handles all the redirects exactly as they say they do.

**Comment by thomasleveil** [comment]
I had the same confusion, and assumed `bats-core` was the runner. `bats-support` seems less confusing.

**Comment by ztombol** [comment]
All right then. I'll rename `bats-core` to `bats-support` sometime **next week**. Here's the list of changes I'll need to make after renaming the repo. Did I miss something?
- bats-support
  - [x] Add renaming notice (temporary) to the top of README.md
  - [x] Update references in README.md
  - [x] Update package.json
- bats-assert
  - [x] Update links in README.md
  - [x] Update package.json
  - [x] Update dependency in .travis.yaml
  - [x] Update test dependency
- bats-docs
  - [x] Update links in README.md
  - [x] Update examples in README.md

_**Update:** Renaming notice is temporary. -- 2016.02.26 20:53 UTC_
_**Update:** Add .travis.yaml now that we have CI. -- 2016.02.27 01:49 UTC_
_**Update:** Timeline changed to next week (as it was originally intended) -- 2016.02.27 13:24 UTC_
_**Update:** `bats-support` renamed and updated. -- 2016.03.01 18:25 UTC_
_**Update:** `bats-assert` updated. -- 2016.03.01 18:45 UTC_
_**Update:** `bats-docs` updated. -- 2016.03.01 19:08 UTC_

**Comment by ztombol** [comment]
`bats-core` has been renamed to `bats-support`. Thanks everyone! :smile:
